<html>
<head>
   <meta http-equiv="content-type" content="text/html; charset=utf-8">
</head>

<body>


<h2>Марки асфальта</h2>
<p>&nbsp;</p>
<p>Действующие цены с 22.09.2014г.</p>
<div>
<table class="MsoNormalTable" style="width: 100%; border-collapse: collapse; border-style: none; padding-top: 5px; padding-bottom: 5px;" border="1" cellpadding="0" cellspacing="0">
<tbody>
<tr>
<td style="width: 221px; border-image: initial; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; border-width: 1pt; border-color: black; border-style: solid;" bgcolor="#E8E8E8" valign="top" width="43%">
<p style="text-align: center;"><strong><span>Асфальтобетонные смеси</span></strong></p>
</td>
<td width="23%" align="center" valign="middle" style="width: 23%; border-style: solid solid solid none; border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; padding: 0cm 5.4pt; background-color: #e8e8e8;" scope="col">
<p style="text-align: center;"><strong><span>Нормативный </span><span>документ</span></strong></p>
</td>
<td style="width: 125px; border-top-style: solid; border-right-style: solid; border-bottom-style: solid; border-top-color: black; border-right-color: black; border-bottom-color: black; border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; border-image: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt;" bgcolor="#E8E8E8" width="26%">
<p style="text-align: center;"><strong><span>Цена за 1 тонну с НДС </span><span><br></span></strong></p>
</td>
</tr>
<tr style="height: 12.95pt;">
  <td style="width: 221px; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: black; border-bottom-color: black; border-left-color: black; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-image: initial; border-top-style: none; border-top-width: initial; border-top-color: initial; padding-top: 0.px; padding-right: 5.4pt; padding-bottom: 2px; padding-left: 5.4pt; height: 12.95pt;" valign="top"><p>Мелкозернистый тип А, марка 1,  МА1</p></td>
  <td style="width: 114px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>ГОСТ 9128-2009</p></td>
  <td style="width: 125px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>2537-00</p></td>
</tr>
<tr style="height: 12.95pt;">
  <td style="width: 221px; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: black; border-bottom-color: black; border-left-color: black; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-image: initial; border-top-style: none; border-top-width: initial; border-top-color: initial; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;" valign="top"><p>Мелкозернистый тип Б, марка 1, МБ1,МБ2</p></td>
  <td style="width: 114px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>ГОСТ 9128-2009</p></td>
  <td style="width: 125px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>2500-00</p></td>
</tr>
<tr style="height: 12.95pt;">
  <td style="width: 221px; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: black; border-bottom-color: black; border-left-color: black; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-image: initial; border-top-style: none; border-top-width: initial; border-top-color: initial; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;" valign="top"><p>Мелкозернистый тип В, марка 2, МВ2</p></td>
  <td style="width: 114px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>ГОСТ 9128-2009</p></td>
  <td style="width: 125px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>2400-00</p></td>
</tr>
<tr style="height: 12.95pt;">
  <td style="width: 221px; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: black; border-bottom-color: black; border-left-color: black; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-image: initial; border-top-style: none; border-top-width: initial; border-top-color: initial; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;" valign="top"><strong style="color:#900">Мелкозернистая, тип I</strong></td>
  <td style="width: 114px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><strong style="color:#900">ТУ 5718-003-11418567-2014</strong></td>
  <td style="width: 125px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><strong  style="color:#900">2100-00</strong></td>
</tr>
<tr style="height: 12.95pt;">
  <td style="width: 221px; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: black; border-bottom-color: black; border-left-color: black; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-image: initial; border-top-style: none; border-top-width: initial; border-top-color: initial; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;" valign="top"><strong style="color:#900">Песчаная, тип II</strong></td>
  <td style="width: 114px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><strong style="color:#900">ТУ 5718-003-11418567-2014</strong></td>
  <td style="width: 125px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><strong  style="color:#900">2100-00</strong></td>
</tr>
<tr style="height: 12.95pt;">
  <td style="width: 221px; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: black; border-bottom-color: black; border-left-color: black; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-image: initial; border-top-style: none; border-top-width: initial; border-top-color: initial; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;" valign="top"><strong style="color:#900">Малощебенистая, МЩ- I</strong></td>
  <td style="width: 114px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><strong style="color:#900">ТУ 5718-004-11418567-2014</strong></td>
  <td style="width: 125px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><strong  style="color:#900">2100-00</strong></td>
</tr>
<tr style="height: 12.95pt;">
  <td style="width: 221px; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: black; border-bottom-color: black; border-left-color: black; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-image: initial; border-top-style: none; border-top-width: initial; border-top-color: initial; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;" valign="top"><p>Песчаный     Л4</p></td>
  <td style="width: 114px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>ТУ  5718-002-0400633-2006</p></td>
  <td style="width: 125px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>2400-00</p></td>
</tr>
<tr style="height: 12.95pt;">
  <td style="width: 221px; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: black; border-bottom-color: black; border-left-color: black; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-image: initial; border-top-style: none; border-top-width: initial; border-top-color: initial; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;" valign="top"><p>Песчаный    ПД II</p></td>
  <td style="width: 114px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>ГОСТ 9128-2009</p></td>
  <td style="width: 125px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>2500-00</p></td>
</tr>
<tr style="height: 12.95pt;">
  <td style="width: 221px; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: black; border-bottom-color: black; border-left-color: black; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-image: initial; border-top-style: none; border-top-width: initial; border-top-color: initial; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;" valign="top"><p>Песчаный на отсеве ПГ</p></td>
  <td style="width: 114px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>ГОСТ 9128-2009</p></td>
  <td style="width: 125px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>2900-00</p></td>
</tr>
<tr style="height: 12.95pt;">
  <td style="width: 221px; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: black; border-bottom-color: black; border-left-color: black; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-image: initial; border-top-style: none; border-top-width: initial; border-top-color: initial; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;" valign="top"><p>Песчаный Пдо3,ПД3,</p></td>
  <td style="width: 114px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>ТУ5718-003-04000633-2006</p></td>
  <td style="width: 125px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>2400-00</p></td>
</tr>
<tr style="height: 12.95pt;">
  <td style="width: 221px; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: black; border-bottom-color: black; border-left-color: black; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-image: initial; border-top-style: none; border-top-width: initial; border-top-color: initial; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;" valign="top"><p>Крупнозернистый плотный,  КБ1,КБ2</p></td>
  <td style="width: 114px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>ГОСТ 9128-2009</p></td>
  <td style="width: 125px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>2500-00</p></td>
</tr>
<tr style="height: 12.95pt;">
  <td style="width: 221px; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: black; border-bottom-color: black; border-left-color: black; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-image: initial; border-top-style: none; border-top-width: initial; border-top-color: initial; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;" valign="top"><p>Крупнозернистый пористый  КП1</p></td>
  <td style="width: 114px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>ГОСТ 9128-2009</p></td>
  <td style="width: 125px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>2400-00</p></td>
</tr>
<tr style="height: 12.95pt;">
  <td style="width: 221px; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: black; border-bottom-color: black; border-left-color: black; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-image: initial; border-top-style: none; border-top-width: initial; border-top-color: initial; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;" valign="top"><p>Литой асфальт, Л5,  Л1</p></td>
  <td style="width: 114px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>ТУ-5718-002-04000633-2006</p></td>
  <td style="width: 125px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>3717-00</p></td>
</tr>
<tr style="height: 12.95pt;">
  <td style="width: 221px; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: black; border-bottom-color: black; border-left-color: black; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-image: initial; border-top-style: none; border-top-width: initial; border-top-color: initial; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;" valign="top"><p>Литой асфальт, Л2,Л3, мелкозерн.   высокоплотный ВП1</p></td>
  <td style="width: 114px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>ГОСТ 9128-2009</p></td>
  <td style="width: 125px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>3127-00</p></td>
</tr>
<tr style="height: 12.95pt;">
  <td style="width: 221px; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: black; border-bottom-color: black; border-left-color: black; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-image: initial; border-top-style: none; border-top-width: initial; border-top-color: initial; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;" valign="top">Литой асфальт на полимерно-битумном вяжущем, Л5 на ПБВ</td>
  <td style="width: 114px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;">&nbsp;</td>
  <td style="width: 125px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;">4543-00</td>
</tr>
<tr style="height: 12.95pt;">
  <td style="width: 221px; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: black; border-bottom-color: black; border-left-color: black; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-image: initial; border-top-style: none; border-top-width: initial; border-top-color: initial; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;" valign="top"><p>Щебеночно-мастичный, ЩМА  15, ЩМА 20</p></td>
  <td style="width: 114px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>ГОСТ 31015-2002</p></td>
  <td style="width: 125px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>3304-00</p></td>
</tr>
<tr style="height: 12.95pt;">
  <td style="width: 221px; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: black; border-bottom-color: black; border-left-color: black; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-image: initial; border-top-style: none; border-top-width: initial; border-top-color: initial; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;" valign="top"><p>Мелкозернистый тип  Б  на вяжущем БИТРЭК</p></td>
  <td style="width: 114px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>СТО  5718-58528024-002-2007</p></td>
  <td style="width: 125px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>3481-00</p></td>
</tr>
<tr style="height: 12.95pt;">
  <td style="width: 221px; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: black; border-bottom-color: black; border-left-color: black; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-image: initial; border-top-style: none; border-top-width: initial; border-top-color: initial; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;" valign="top"><p>Мелкозернистый тип  А  на вяжущем БИТРЭК</p></td>
  <td style="width: 114px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>СТО  5718-58528024-002-2007</p></td>
  <td style="width: 125px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>3481-00</p></td>
</tr>
<tr style="height: 12.95pt;">
  <td style="width: 221px; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: black; border-bottom-color: black; border-left-color: black; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-image: initial; border-top-style: none; border-top-width: initial; border-top-color: initial; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;" valign="top"><p>Мелкозернистый тип  Б  на полимерно вяжущем ПБВ</p></td>
  <td style="width: 114px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>ГОСТ 9128-2009</p></td>
  <td style="width: 125px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>3481-00</p></td>
</tr>
<tr style="height: 12.95pt;">
  <td style="width: 221px; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: black; border-bottom-color: black; border-left-color: black; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-image: initial; border-top-style: none; border-top-width: initial; border-top-color: initial; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;" valign="top"><p>Асфальтобетонная смесь для  устройства шероховатого</p>
    <p>    тонкослойного покрытия  ШТП</p></td>
  <td style="width: 114px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>&nbsp;</p></td>
  <td style="width: 125px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>3304-00</p></td>
</tr>
<tr style="height: 12.95pt;">
  <td height="48" valign="top" style="width: 221px; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: black; border-bottom-color: black; border-left-color: black; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-image: initial; border-top-style: none; border-top-width: initial; border-top-color: initial; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>Щебеночно-мастичный асфальт,  ЩМА на вяжущем БИТРЭК</p></td>
  <td style="width: 114px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>СТО 5718-58528024-002-2007</p></td>
  <td style="width: 125px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>4500-00</p></td>
</tr>
<tr style="height: 12.95pt;">
  <td style="width: 221px; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: black; border-bottom-color: black; border-left-color: black; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-image: initial; border-top-style: none; border-top-width: initial; border-top-color: initial; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;" valign="top"><p>Щебёночно-мастичный  асфальт на вяжущем  ПБВ, ЩМА ПБВ</p></td>
  <td style="width: 114px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>СТО 61595504-003-2010</p></td>
  <td style="width: 125px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>4400-00</p></td>
</tr>
<tr style="height: 12.95pt;">
  <td style="width: 221px; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: black; border-bottom-color: black; border-left-color: black; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-image: initial; border-top-style: none; border-top-width: initial; border-top-color: initial; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;" valign="top"><p>Холодный асфальт, ХА</p></td>
  <td style="width: 114px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>ТУ 571841-002-11418567-2005</p></td>
  <td style="width: 125px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>6670-00</p></td>
</tr>
<tr style="height: 12.95pt;">
  <td style="width: 221px; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: black; border-bottom-color: black; border-left-color: black; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-image: initial; border-top-style: none; border-top-width: initial; border-top-color: initial; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;" valign="top"><p>Черный щебень ЧЩ</p></td>
  <td style="width: 114px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>ТУ 400-24-163-89</p></td>
  <td style="width: 125px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>2360-00</p></td>
</tr>
<tr style="height: 12.95pt;">
  <td style="width: 221px; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: black; border-bottom-color: black; border-left-color: black; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-image: initial; border-top-style: none; border-top-width: initial; border-top-color: initial; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;" valign="top"><p>Горячий щебень, ГЩ</p></td>
  <td style="width: 114px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>ГОСТ 8267-93</p></td>
  <td style="width: 125px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>2250-00</p></td>
</tr>
<tr style="height: 12.95pt;">
  <td style="width: 221px; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: black; border-bottom-color: black; border-left-color: black; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-image: initial; border-top-style: none; border-top-width: initial; border-top-color: initial; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;" valign="top"><p>Горячий песок  ГП</p></td>
  <td style="width: 114px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>ТУ  400-24-163-89</p></td>
  <td style="width: 125px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>1298-00</p></td>
</tr>
<tr style="height: 12.95pt;">
  <td style="width: 221px; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: black; border-bottom-color: black; border-left-color: black; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-image: initial; border-top-style: none; border-top-width: initial; border-top-color: initial; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;" valign="top"><p>Черный песок  ЧП</p></td>
  <td style="width: 114px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>&nbsp;</p></td>
  <td style="width: 125px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>1652-00</p></td>
</tr>
<tr style="height: 12.95pt;">
  <td style="width: 221px; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: black; border-bottom-color: black; border-left-color: black; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-image: initial; border-top-style: none; border-top-width: initial; border-top-color: initial; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;" valign="top"><p>Цветной асфальт Красно-коричневый ЦАКК</p></td>
  <td style="width: 114px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>ТУ 5718-001-1148567-03</p></td>
  <td style="width: 125px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>9676-00</p></td>
</tr>
<tr style="height: 12.95pt;">
  <td style="width: 221px; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: black; border-bottom-color: black; border-left-color: black; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; border-image: initial; border-top-style: none; border-top-width: initial; border-top-color: initial; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;" valign="top"><p>Битум горячий</p></td>
  <td style="width: 114px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>ГОСТ  22245-90</p></td>
  <td style="width: 125px; border-top-style: none; border-top-width: initial; border-top-color: initial; border-left-style: none; border-left-width: initial; border-left-color: initial; border-bottom-style: solid; border-bottom-color: black; border-bottom-width: 1pt; border-right-style: solid; border-right-color: black; border-right-width: 1pt; padding-top: 0cm; padding-right: 5.4pt; padding-bottom: 0cm; padding-left: 5.4pt; height: 12.95pt;"><p>20827-00</p></td>
</tr>
</tbody>
</table>
</div>
<p>&nbsp;</p>
<p>* Доставка асфальтобетона, крошки, щебня, песка за 1 тн до 20 км – 300 руб с НДС, свыше 20 км дополнительно 6 руб. с НДС за каждый км, минимальная оплата за 12тн</p>
<p>&nbsp;</p>
<p>109429, г. Москва, ул. Верхние Поля, 54, тел/факс 359-75-25</p>
<p>&nbsp;</p>


</body>

</html>